apply plugin: 'com.android.application'

android {
    defaultConfig {
        compileSdk 36
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 5
        versionName "1.5"
        testInstrumentationRunner "android.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig = true
    }

    packaging {
        resources {
            excludes += ['META-INF/versions/9/OSGI-INF/MANIFEST.MF']
        }
    }

    namespace 'com.halil.ozel.movieparadise'
}

dependencies {
    // AndroidX UI
    implementation 'androidx.core:core:1.18.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.leanback:leanback:1.2.0'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'androidx.annotation:annotation:1.10.0'

    // Network and JSON
    implementation "com.squareup.retrofit2:retrofit:3.0.0"
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation "com.squareup.retrofit2:adapter-rxjava3:3.0.0"
    implementation "com.squareup.okhttp3:okhttp:5.3.2"
    implementation "com.squareup.okhttp3:logging-interceptor:5.3.2"
    implementation 'com.google.code.gson:gson:2.14.0'

    // Images
    implementation 'com.github.bumptech.glide:glide:5.0.7'
    annotationProcessor 'com.github.bumptech.glide:compiler:5.0.7'

    // Reactive streams
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation 'io.reactivex.rxjava3:rxjava:3.1.12'

    // Dependency injection
    implementation 'com.google.dagger:dagger:2.59.2'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.59.2'
}
